### ISSUE TITLE
Actualizar componente Input (text)

### ISSUE THREAD

**Issue by nykka** [frontendcafe/water-call-for-papers#103]
## Actualizar componente Input (text) en base al diseño

Diseño: https://www.figma.com/file/yqFuCDsK4VAVoV7RAYkn0M/Proceso-diseño-CMYK?node-id=811%3A10360z

Imagen:
![Image](https://user-images.githubusercontent.com/8450941/186780070-acbfe484-c3b6-4591-ab79-df3986c75aaa.png)

**Comment by yolitzr** [comment]
Estos cambios estan en la [PR 106](https://github.com/frontendcafe/water-call-for-papers/pull/106)
