### ISSUE TITLE
Crear componente button

### ISSUE THREAD

**Issue by nykka** [frontendcafe/water-call-for-papers#12]
## Crear un componente button y su story en storybook
Wireframes:
https://www.figma.com/file/yqFuCDsK4VAVoV7RAYkn0M/Proceso-dise%C3%B1o-CMYK?node-id=196%3A1270
Documentación de ayuda:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
https://www.w3.org/WAI/ARIA/apg/patterns/button/

El button debe tener:
- Label (requerido): visible u oculto
- OnClick (requerido)
- Icono (opcional): a la derecha o a la izquierda
- Style (requerido): primary, secondary, etc
- Size (requerido): lg, md, sm

Los estados que va a tener el button son:
- Focus
- Active
- Disabled
- Loading / Saving (spinner)

Observaciones:
Si el botón va a tener solo un ícono, igual va a tener un label pero este debería estar _visually hidden_ para que sea accesible a través de los lectores de pantalla 
https://www.a11yproject.com/posts/how-to-hide-content/

**Comment by TonyMckes** [comment]
Pregunta sobre los puntos;
> Label (requerido): visible u oculto

> Observaciones:
Si el botón va a tener solo un ícono, igual va a tener un label pero este debería estar visually hidden para que sea accesible a través de los lectores de pantalla
https://www.a11yproject.com/posts/how-to-hide-content/

Puede ser que el boton tenga solo un icono y en ese caso en lugar de un "label"(text content) se le agrega un aria-label? 
Al menos es lo que he leido de [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label), pero no se si me estoy pasando algo

> Most content has an accessible name generated from its immediate wrapping element's text content. Accessible names can also be created by certain attributes or associated elements.

> By default, a button's accessible name is the content between the opening and closing [`<button>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) tags, an image's accessible name is the content of its [`alt`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-alt) attribute, and a form input's accessible name is the content of the associated [`<label>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) element.

> If none of these options are available, or if the default accessible name is not appropriate, use the aria-label attribute to define the accessible name of an element.
