### ISSUE TITLE
Crear servicio para crear un evento

### ISSUE THREAD

**Issue by franmper** [frontendcafe/water-call-for-papers#21]
Crear servicio para poder añadir un evento a la db de firebase

https://firebase.google.com/docs/firestore/manage-data/add-data#set_a_document

- El id debería ser autogenerado
- Si el organizador no existe deberá ser agregado en la db de Organizers (probablemente sea necesario utilizar la funcion creada en este issue https://github.com/frontendcafe/water-call-for-papers/issues/22)

**Comment by bryanedward** [comment]
Buenas noches  mr @franmper  en crear el evento donde sugiere crear el organizador si no existe , no sabia que poner en el nombre,  lo he dejado con comillas por el momento, espero indicaciones ✌️
