### ISSUE TITLE
Crear el componente Image

### ISSUE THREAD

**Issue by nykka** [frontendcafe/water-call-for-papers#69]
## Crear un componente Image y su correspondiente story en Storybook.

Wireframes:
https://www.figma.com/file/yqFuCDsK4VAVoV7RAYkn0M/Proceso-dise%C3%B1o-CMYK?node-id=479%3A5067
Documentación de ayuda:
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
https://css-tricks.com/using-webp-images/

Algunos comportamientos/props esperados del componente:
- Images (requerido) jpg y webp
- Alt text (requerido)
- Que sea responsive

**Comment by ErikGIovani** [comment]
¿Cuántos tamaños de imagen va a haber?
