### ISSUE TITLE
Crear el componente Filtro (Dropdown)

### ISSUE THREAD

**Issue by nykka** [frontendcafe/water-call-for-papers#73]
## Crear un componente Menu (Filtro) y su correspondiente story en Storybook.

Wireframes:
https://www.figma.com/file/yqFuCDsK4VAVoV7RAYkn0M/Proceso-dise%C3%B1o-CMYK?node-id=479%3A5067
Documentación de ayuda:
https://headlessui.com/react/menu
https://www.w3.org/WAI/ARIA/apg/patterns/menu/
https://www.w3.org/WAI/ARIA/apg/patterns/menubutton/

Imagen
![Image](https://user-images.githubusercontent.com/8450941/185678491-1de887cc-e22d-4256-95f5-78b4157267bc.png)

Algunos comportamientos esperados del componente:
- Children (requerido): Los filtros
- Tiene que ser accesible con teclado
- Tiene que cerrarse apretando escape
- Tiene que cerrarse apretando fuera del dropdown

**Comment by nykka** [comment]
Este componente depende del compponente Radio y del componente Tag~

**Comment by franmper** [comment]
Links con diseños actualizados

https://www.figma.com/file/yqFuCDsK4VAVoV7RAYkn0M/Proceso-dise%C3%B1o-CMYK?node-id=1615%3A27778
https://www.figma.com/file/yqFuCDsK4VAVoV7RAYkn0M/Proceso-dise%C3%B1o-CMYK?node-id=1565%3A26435
https://www.figma.com/file/yqFuCDsK4VAVoV7RAYkn0M/Proceso-dise%C3%B1o-CMYK?node-id=1560%3A26255

Prototipo:

https://www.figma.com/proto/yqFuCDsK4VAVoV7RAYkn0M/Proceso-dise%C3%B1o-CMYK?node-id=1488%3A20494&scaling=min-zoom&page-id=759%3A6775&starting-point-node-id=1488%3A20812&show-proto-sidebar=1
