### ISSUE TITLE
Investigar el componente Day Picker

### ISSUE THREAD

**Issue by nykka** [frontendcafe/water-call-for-papers#76]
## Investigar/Buscar una libreria para el componente Day Picker 

ESTA TAREA ES SOLO DE INVESTIGACION. Una vez que encuentres una o varias librerias, vamos a ver en equipo cual el las mejor para avanzar con el componente.

Buscar una librería que sea accesible y que sirva para este uso.

**Comment by ErikGIovani** [comment]
## Es la mejor alternativa que he encontrado y es accesible
https://react-day-picker.js.org/

**Comment by franmper** [comment]
dejo otra opción, no se si la pudiste ver @ErikGIovani https://www.npmjs.com/package/react-datepicker

**Comment by ErikGIovani** [comment]
@franmper No la había visto, pero también es buena opción 🥳
