### ISSUE TITLE
Agregar icono al componente Input (text)

### ISSUE THREAD

**Issue by nykka** [frontendcafe/water-call-for-papers#79]
Cuando esté listo el componente Icons, refactorear el componente input (text) para que tenga esa opción.

**Comment by yolitzr** [comment]
Creo que esta issue ya esta, la colco en Review para verificar

**Comment by yolitzr** [comment]
Tarea lista en [MR #106 ](https://github.com/frontendcafe/water-call-for-papers/pull/106)
