### ISSUE TITLE
Agregar endpoint para temas (topics)

### ISSUE THREAD

**Issue by franmper** [frontendcafe/water-call-for-papers#88]
BLOQUEADO POR [PR](https://github.com/frontendcafe/water-call-for-papers/pull/80)

Se deberá configurar la API para los temas (topics)

```
/GET sin params trae todos los temas ej: `http://localhost:3000/api/topics`
/POST para crear un topic 
```

**Comment by rolivencia** [comment]
@franmper consideraría el subdividir las tareas una por endpoint. Si te parece las armo. Ídem para el caso de #87.

**Comment by rolivencia** [comment]
Cerrado luego de la creación de #95 y #96, que especifican los mismos requerimientos con menor granularidad.
